/* Wijzigingslogboek van de demo — nieuwste onderaan.
   Met terugwerkende kracht opgebouwd uit de versiegeschiedenis (24-09-2026).
   Werkwijze: bij elke nieuwe versie één regel erbij, in gewone taal. De versiecode is pas na
   de commit bekend: zet eerst 'deze versie' en vul de code in bij de commit daarna.
   d = datum, o = wat, x = toelichting voor Jack, v = versiecode(s). */
var WIJZIGINGEN=[
 {d:"2026-07-23",o:"Eerste demo-concept",x:"Opzet van de ontdeksite in de huisstijl van Whiskysite, in vijf opeenvolgende versies tussen 11 en 23 juli.",v:"ef387bb–3642297"},
 {d:"2026-08-24",o:"Voortgangspagina en toegangscode",x:"Beheeromgeving kreeg een pagina met de stand van het project en de rolverdeling. De demo vraagt voortaan om een toegangscode.",v:"a8014d5, 110720a, c43b485"},
 {d:"2026-08-24",o:"Rustigere productkaarten op de homepage",x:"Smaaktags en smaakbalkjes staan alleen nog op de productpagina.",v:"3c2fce6"},
 {d:"2026-08-24",o:"Archief van vragen en voortgang",x:"Alle afgestemde vragen en projectstappen doorzoekbaar onderaan deze pagina; de vragenlijst toont alleen wat nog openstaat.",v:"c4f21ad, c465452, 1998719"},
 {d:"2026-08-24",o:"Vragen over tekst en schrijfstijl",x:"Vragenlijst aangevuld na de tekstanalyse.",v:"b021380, 7ef52fe, a467b2f"},
 {d:"2026-08-25",o:"Collectie: filteren en sorteren",x:"Filters met het aantal flessen per keuze, echte sorteringen, filterstand in de link zodat je een selectie kunt delen, filterpaneel op mobiel. Filterstand blijft staan bij een klik op een categorie.",v:"be2af56, 1721286, e3c7585"},
 {d:"2026-08-25",o:"Streekpagina Campbeltown als sjabloon",x:"Eerste streekpagina, met roterend beeld en per foto de herkomst, maker en licentie (Wikimedia Commons).",v:"be2af56, 7f6219f, ac42c37"},
 {d:"2026-08-25",o:"Scherm Beeldvoorstellen",x:"Beelden goedkeuren, afwijzen, op volgorde zetten of een eigen foto toevoegen. De streekpagina toont het goedgekeurde beeld.",v:"e9d6d8a"},
 {d:"2026-08-26",o:"Kaart in atlasstijl",x:"Wereld met whiskylanden en Schotland met 47 distilleerderijen per streek, met doorklik naar collectie of streekpagina. Geen externe kaartdienst.",v:"9663851, 4e1995e, 6504b22"},
 {d:"2026-08-29",o:"Bronnen en partners",x:"Overzicht van reviewbronnen en partners in de beheeromgeving; vragenlijst bijgewerkt.",v:"eafeaf1, 96070b2"},
 {d:"2026-09-01",o:"Reviewers bijgewerkt",x:"Conceptreviews en de lijst met reviewers aangepast.",v:"70f1816, bdcf328, dc0fb28"},
 {d:"2026-09-02",o:"Beheeromgeving afgeschermd",x:"Niet vindbaar voor zoekmachines, en bereikbaar via een discrete ingang.",v:"c08a1e7, eb2d959"},
 {d:"2026-09-02",o:"Echte catalogus in de demo",x:"De demo draait op de werkelijke producten uit de winkel. Wizard, sommelier en vergelijken werken op de hele catalogus.",v:"f82073e, 8ce501a, 89627ff"},
 {d:"2026-09-03",o:"Beoordelen per fles",x:"Beoordeelscherm met de echte wachtrij. Per fles omschrijving, smaakprofiel en bron op één kaart, bij te stellen op de productpagina zelf.",v:"f7cf9db, 8415a89, eb02b1f, ff85b9e, 07b7c31"},
 {d:"2026-09-03",o:"Antwoorden van Jack verwerkt",x:"Vragenlijst bijgewerkt; voortgangspagina herkenbaar gelinkt.",v:"8e9219c, 17c8c8e, 730b6c1"},
 {d:"2026-09-15",o:"Productfoto's: eerste resultaten",x:"Voor-en-na van twintig flessen: vrijgemaakt van de achtergrond en op een vaste hoogte, zodat een rij flessen rustig oogt.",v:"9175d9c"},
 {d:"2026-09-24",o:"Vier smaakassen",x:"Rook, zoet, fruit en kruidig, op een schaal van vijf. De smaakwizard rekent weer goed. Nieuw filter Maritiem. De volgorde bij 'lijkt op deze fles' is niet langer toevallig.",v:"31e898f"},
 {d:"2026-09-24",o:"Smaakfilter hersteld, smaakprofielen compleet",x:"De smaakfilters en de tegels op de homepage werken weer. Elke fles met een smaakprofiel heeft nu vier assen; waar een as geschat is, staat in het beoordeelscherm waarop.",v:"482788a"},
 {d:"2026-09-24",o:"Wijzigingslogboek",x:"Dit logboek: elke versie van de demo met datum en toelichting, terug tot het eerste concept.",v:"544d64c"},
 {d:"2026-09-24",o:"Beeldtool in de beheeromgeving",x:"Productfoto kiezen of uit de catalogus halen: een egale achtergrond gaat weg, de fles komt gecentreerd op 92% van de hoogte en het resultaat is doorzichtig. Voorbeeld op wit, crème, grijs of donker, en downloaden als WebP of PNG. Alles gebeurt in de browser; er wordt niets geüpload.",v:"544d64c"},
 {d:"2026-09-25",o:"Archief op volgorde van datum",x:"Vragen, projectstappen en wijzigingen staan in één tijdlijn, nieuwste bovenaan, in plaats van per soort. Lopende en geplande stappen staan helemaal bovenaan.",v:"1007cd8"},
 {d:"2026-09-25",o:"Afstemming in het archief",x:"Afspraken uit overleg en mail met Whiskysite staan nu ook in de tijdlijn van het archief, met datum en kanaal.",v:"1007cd8"},
 {d:"2026-09-25",o:"Samples herkenbaar als sample",x:"Een sample die de foto van zijn hoofdfles leent, krijgt nu een schuine SAMPLE-band over de fles en linksonder de inhoud (bijvoorbeeld 6 CL) — het ontwerp van de voor-en-na-pagina. Voorheen stond alleen de inhoud erbij.",v:"1007cd8"},
 {d:"2026-09-25",o:"Productfoto's automatisch opgemaakt",x:"De site toont voortaan per fles het opgemaakte beeld (achtergrond weg, fles op vaste hoogte) zodra dat klaarstaat, en anders de winkelfoto. Samples krijgen het beeld van hun hoofdfles. Foto's die de automatische opmaak niet aankan, staan in de beeldtool onder Aandacht nodig.",v:"1007cd8"},
 {d:"2026-09-27",o:"Beoordelen en Hiatenlijst: inloggen en opslaan",x:"Beoordelen en de nieuwe Hiatenlijst worden na inloggen direct opgeslagen, op elk apparaat. Bij de herkomstvragen staat wat er nu in de demo staat; bij vat en turf dat het voorstel al zichtbaar is. De Hiatenlijst bevat de open punten uit de whiskykennisbank, in te vullen in je eigen tempo.",v:"1007cd8"},
 {d:"2026-09-28",o:"Hiatenlijst wordt 'Vragen voor Jack'",x:"De ruim 270 losse punten zijn teruggebracht tot 20 heldere vragen, per thema. Bij elke vraag staat wat we nu weten, met keuzeknoppen of een open antwoordveld. Dubbele en vage punten zijn samengevoegd; puur onderzoekswerk blijft in de kennisbank. Je eerdere antwoord over de Nederlandse distilleerderijen is meegenomen.",v:"99f6931"},
 {d:"2026-09-28",o:"Antwoorden komen aan en je ziet wat ermee gebeurt",x:"Bij elk antwoord en elk beoordelingsbesluit staat nu of het is opgeslagen, door de kennisbank is opgehaald of al is verwerkt, met een korte toelichting. Ophalen gebeurt drie keer per dag (09:51, 13:51, 17:51). Hersteld: besluiten die je vóór het inloggen had genomen, gaan nu direct mee naar de opslag, en bij 19 flessen overschreef het turfbesluit het vatbesluit (of andersom); die hebben nu elk een eigen plek.",v:"eac35d9"},
 {d:"2026-09-28",o:"Neutrale fles bij ontbrekende foto",x:"Heeft een fles geen werkende foto (ook niet in de webwinkel), dan toont de site een neutrale fles met \"foto volgt\" in plaats van een kapot plaatje.",v:"02a7c6d"},
 {d:"2026-09-28",o:"Streekpagina: flessen direct onder de intro",x:"Op de streekpagina staan de flessen nu direct onder het introblok. 'Hoe smaakt het' is weg (stond al in de intro). 'Wie er zit' is verhuisd naar een streekgids onder Inspiratie, met een link vanaf de streekpagina.",v:"3ea22ab"},
 {d:"2026-09-29",o:"Beeldtool: opgemaakte foto meteen op de site",x:"Kies je een fles uit 'Aandacht nodig' of de catalogus, dan heet de download naar het product-ID, staat het opgemaakte beeld direct op de productpagina en gaat de fles van de aandachtslijst af. Onderaan zie je welke beelden nog gepusht moeten worden. Voor iedereen zichtbaar na het inladen en pushen.",v:"6446ea4"},
 {d:"2026-09-29",o:"Uitgelicht: echte flessen uit de webwinkel",x:"De uitgelichte flessen op de homepage en elders waren verzonnen demoproducten met eigen prijzen en SALE-labels. Het zijn nu 16 echte producten uit de catalogus, met de echte naam, prijs en het opgemaakte beeld. Elke productpagina heeft een knop naar dezelfde fles op whiskysite.nl. Lagavulin 16, Oban 14, Glenmorangie 21 en Bruichladdich Old Skool vervallen tot Jack kiest. Het blok 'Zomerse aanbiedingen' heet nu 'Uitgelicht' en toont alleen flessen op voorraad; de hero toont de eerste daarvan.",v:"6ffa1f4"},
 {d:"2026-09-29",o:"Beeldtool: juiste vervolgstap na downloaden",x:"De beeldtool verwijst nu naar start-beelden.ps1 -Handmatig. Dat neemt de gedownloade beelden op in de beeldpijplijn, beschermt ze tegen een volgende automatische run en publiceert ze naar de demo.",v:"f4b80ef"},
 {d:"2026-09-29",o:"Twee proefteksten voor Jack",x:"Onder Vragen voor Jack staat een nieuw thema Schrijfstijl met twee flessen: Kilkerran 12 (nu zonder tekst) en Longrow Peated (bestaande tekst herschreven). Per fles drie versies om uit te kiezen. Gebouwd volgens Jacks antwoorden van 24 augustus: je-vorm, voor de nieuwsgierige beginner, geen superlatieven of scores.",v:"431dba1"},
 {d:"2026-09-29",o:"Beeldtool: opslaan zet de foto direct op de site",x:"Na inloggen zet 'Opslaan op de site' de opgemaakte foto meteen op de productpagina, voor iedere bezoeker. Geen download meer en geen technische vervolgstap. De bewerking zelf blijft in de browser gebeuren.",v:"4effee9"},
 {d:"2026-09-29",o:"Beheer: overzicht en duidelijke indeling",x:"De beheeromgeving opent met een overzicht: wat er op je wacht, hoe ver de bouw is en een doorkijk naar de toekomstige backend. De zijbalk is verdeeld in drie groepen: groen werkt al met echte gegevens, goud is de stand van de bouw, gestippeld is een voorbeeld met verzonnen cijfers. Het oude dashboard heet nu Winkeldashboard.",v:"deze versie"}
];
